apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-deployment-account
  labels:
    app: service-account
spec:
  replicas: 1
  selector:
    matchLabels:
      app: service-account
  template:
    metadata:
      labels:
        app: service-account
    spec:
      containers:
      - name: app-account
        image: valentinareinoso/aforo255-nodejs-account-vrr:v-3
        ports:
        - containerPort: 5002
        env:
        - name: NACOS_SERVERADDR
          value: "165.227.250.67:8848"
        - name: NACOS_NAMESPACE
          value: "aforo255"
        - name: NACOS_IDENTITYKEY
          value: "nacos"
        - name: NACOS_IDENTITYVALUE
          value: "nacos"
        - name: NACOS_ENV
          value: "PROD"